### ISSUE TITLE
@urql/core direct API calls are not shown

### ISSUE THREAD

**Issue by desmap** [FormidableLabs/urql-devtools#267]
I use a lot direct calls, e.g. `client.mutation()` for stuff like saving and these do not show up in the devtool. Other hook-based calls are shown.

**Comment by andyrichardson** [comment]
Hey @desmap thanks for reporting this.  I'm going to flag this as a bug but we're going to need a little more info in order to work out what is going on. 

We have a [template project here](https://codesandbox.io/s/github/FormidableLabs/urql/tree/main/packages/react-urql/examples/1-getting-started?file=/src/index.tsx) which you could fork or feel free to provide some detailed steps / example code.

> Other hook-based calls are shown.

FYI, it's possible that the exchange is only reporting hook based calls but this is unlikely. The interception of debugging events is [done inside of the client](https://github.com/FormidableLabs/urql-devtools-exchange/blob/master/src/exchange.ts#L33) so there shouldn't be any bias for hooks in particular. 

Are you getting any errors in the console?

**Comment by andyrichardson** [comment]
@desmap I'm going to go ahead and close this as it's getting stale but feel free to drop a comment if you're able to provide more info!
