### ISSUE TITLE
Only Teardown operations visible

### ISSUE THREAD

**Issue by Elijen** [FormidableLabs/urql-devtools#92]
Client setup:
```TypeScript
export const clientFactory = (user: UserContextType) =>
  createClient({
    url: getClientUrl(user),
    fetchOptions: () => {
      return {
        mode: "cors",
        method: "POST"
      };
    },
    exchanges: [cacheExchange, dedupExchange, fetchExchange, devtoolsExchange]
  });

export const Provider = ({ children }) => {
  const user = useContext(UserContext);
  return <DefaultProvider value={clientFactory(user)}>{children}</DefaultProvider>;
};
```

Only Teardown operations visible in events:
<img width="589" alt="Screen Shot 2019-12-13 at 17 17 23" src="https://user-images.githubusercontent.com/1304054/70815098-2a18f000-1dcd-11ea-822e-ae0a1e8c69da.png">

Nothing visible in explorer:
<img width="574" alt="Screen Shot 2019-12-13 at 17 17 28" src="https://user-images.githubusercontent.com/1304054/70815102-2c7b4a00-1dcd-11ea-9e10-99114e05abb2.png">

Multiple requests are made successfully:
<img width="734" alt="Screen Shot 2019-12-13 at 17 17 38" src="https://user-images.githubusercontent.com/1304054/70815181-56347100-1dcd-11ea-9856-9ef8c6d5803b.png">

`Chrome extension: 0.0.6`
`@urql/devtools: 0.1.2`

**Comment by andyrichardson** [comment]
Hey @Elijen this is due to the order of your exchanges.

In short, the `fetch` exchange will not forward operations it can handle itself (i.e. any query). See [the docs](https://formidable.com/open-source/urql/docs/architecture/#exchanges) for more info on how exchanges work.

To fix this issue, make sure your exchange ordering makes sense:

Before
`[cacheExchange, dedupExchange, fetchExchange, devtoolsExchange]`

After
`[dedupExchange, devtoolsExchange, cacheExchange, fetchExchange]`

Closing this but drop a comment if it's you have any more questions about this :+1:
